[workspace]
name = "2026-polymers-workshop"
description = "Fit an OpenFF SMIRNOFF force field to a polymer (PEG) with smee + descent, then simulate single-chain radius of gyration with OpenMM + MDAnalysis."
authors = ["OpenFF <info@openforcefield.org>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]
license = "MIT"

[dependencies]
python = ">=3.12,<3.13"

openff-toolkit = ">=0.17.1"
openff-nagl-base = ">=0.5.2"
openff-nagl-models = "*"
openff-qcsubmit = ">=0.57.0"
qcportal = "*"
openff-packmol = "*"
packmol = "*"
rdkit = ">=2024.09"
# pablo dependencies
rustworkx = "*"
pyxdg = "*"
gemmi = "*"

smee = ">=0.17.0"
descent = ">=0.6.0"
pytorch = ">=2.6"
# pytorch-lightning: exclude 2.6.2 and 2.6.3 (known malware).
pytorch-lightning = ">=2.6.0,!=2.6.2,!=2.6.3"
tensorboard = "*"
tensorboardx = ">=2.6.2.2"

mdanalysis = ">=2.10"
matplotlib = ">=3.10.5"
pandas = ">=2.0"
polars = ">=1.33.1"
statsmodels = "*"
pydantic = ">=2.0,<3"
json5 = ">=0.12.1"
altair = ">=5.4.0"

datasets = "*"

openmm-ml = ">=1.5"
ase = "*"
smirnoff-plugins = ">=0.0.4"
loguru = "*"
mdtraj = "*"
h5py = "*"
# ambertools = "*"

jupyterlab = ">=4"
ipywidgets = ">=8"
nglview = ">=3.0.6,<3.1.0"
ipython = "*"
jupyterlab_execute_time = "*"
jupyterlab-lsp = "*"
jedi-language-server = "*"
jupyterlab_code_formatter = "*"
black = "*"
isort = "*"
tqdm = "*"

pip = "*"
git = "*"

[pypi-dependencies]
swiftpol = { git = "https://github.com/matta-research-group/SwiftPol.git", branch = "main" }
mace-torch = "*"
# Presto: could install v0.8.1 from conda-forge, but missing patch to remove
# malicious polyfill.js ; wait to v0.8.2 for conda-forge install to be safe
presto = { git = "https://github.com/cole-group/presto.git", branch = "main" }
# openff-pablo is not on PyPI / conda-forge yet.
openff-pablo = { git = "https://github.com/openforcefield/openff-pablo.git", branch = "main" }

[tasks]
workshop = "jupyter lab --ServerApp.iopub_data_rate_limit=10000000 peg_workshop_combined.ipynb"

# cuda for gpu acceleration
[feature.cuda]
platforms = ["linux-64"]
system-requirements = { cuda = "12.9" }

[feature.cuda.dependencies]
cuda-version = "12.9.*"
pytorch-gpu = ">=2.6"

[environments]
cuda = ["cuda"]
